// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkmz6aZLDjMzusUhgWFckAeKJ7_NwUdPs',
    appId: '1:952495859705:web:1ba4bcb5f3744838bcbf28',
    messagingSenderId: '952495859705',
    projectId: 'chat-sc-app',
    authDomain: 'chat-sc-app.firebaseapp.com',
    storageBucket: 'chat-sc-app.appspot.com',
    measurementId: 'G-BM8VVHLGHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkEhXlENECDm5_1ITyonECtemJOQdYk0',
    appId: '1:952495859705:android:4e176579bcfbe89dbcbf28',
    messagingSenderId: '952495859705',
    projectId: 'chat-sc-app',
    storageBucket: 'chat-sc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0gunnZqgb8Lf24UgIe5X30q-_1MpJdY',
    appId: '1:952495859705:ios:a75d5e19679f5477bcbf28',
    messagingSenderId: '952495859705',
    projectId: 'chat-sc-app',
    storageBucket: 'chat-sc-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT0gunnZqgb8Lf24UgIe5X30q-_1MpJdY',
    appId: '1:952495859705:ios:a75d5e19679f5477bcbf28',
    messagingSenderId: '952495859705',
    projectId: 'chat-sc-app',
    storageBucket: 'chat-sc-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkmz6aZLDjMzusUhgWFckAeKJ7_NwUdPs',
    appId: '1:952495859705:web:c0a4b5e115cda8ebbcbf28',
    messagingSenderId: '952495859705',
    projectId: 'chat-sc-app',
    authDomain: 'chat-sc-app.firebaseapp.com',
    storageBucket: 'chat-sc-app.appspot.com',
    measurementId: 'G-CR35RMKPNF',
  );
}
